pipeline {
  agent any
  options {
    durabilityHint("PERFORMANCE_OPTIMIZED")
    timeout(time: 3, unit: "DAYS")
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }
   environment {
    git_credentials = credentials("GITHUB_CREDENTIALS")
  }
  stages {
    stage("Checkout") {
      steps {
        checkout([$class: "GitSCM", 
          branches: [[name: "${branchName}"]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [], 
          submoduleCfg: [], 
                  userRemoteConfigs: [[credentialsId: "${git_credentials}", url: "https://github.com/Darshinikannan/Karate.git"]]]
        )
      }
    }
    stage("Build") {
      steps {
        sh "mvn clean install"
        def pom = readMavenPom file:'pom.xml'
        echo pom.version
      }
    }
  }
}
