pipeline {
  agent any
  options {
    durabilityHint("PERFORMANCE_OPTIMIZED")
    timeout(time: 3, unit: "DAYS")
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }
  stages {
    stage("Checkout") {
      steps {
        checkout([$class: "GitSCM", 
          branches: [[name: "main"]], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [], 
          submoduleCfg: [], 
                  userRemoteConfigs: [[credentialsId: "${GITHUB_CREDENTIALS}", url: "https://github.com/Darshinikannan/sample-app-for-ptc.git"]]]
        )
      }
    }
    stage("Build") {
      steps {
        sh "./gradlew clean build"
      }
    }
  }
}
